//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace motor.logic.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDocument
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string SSN { get; set; }
        public string LicenseNumber { get; set; }
        public byte[] VehiclePicture1 { get; set; }
        public byte[] VehiclePicture2 { get; set; }
        public byte[] LicensePicture { get; set; }
        public short Status { get; set; }
        public string VehicleNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
